// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks.proto

package br.ortiz.grpc.services;

public interface QuoteQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.QuoteQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue symbol = 1;</code>
   * @return Whether the symbol field is set.
   */
  boolean hasSymbol();
  /**
   * <code>.google.protobuf.StringValue symbol = 1;</code>
   * @return The symbol.
   */
  com.google.protobuf.StringValue getSymbol();
  /**
   * <code>.google.protobuf.StringValue symbol = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getSymbolOrBuilder();
}
