// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks.proto

package br.ortiz.grpc.services;

public interface QuoteMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.QuoteMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   * @return The id.
   */
  com.google.protobuf.Int64Value getId();
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder();

  /**
   * <code>.google.protobuf.StringValue symbol = 2;</code>
   * @return Whether the symbol field is set.
   */
  boolean hasSymbol();
  /**
   * <code>.google.protobuf.StringValue symbol = 2;</code>
   * @return The symbol.
   */
  com.google.protobuf.StringValue getSymbol();
  /**
   * <code>.google.protobuf.StringValue symbol = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getSymbolOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value date = 3;</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Int64Value date = 3;</code>
   * @return The date.
   */
  com.google.protobuf.Int64Value getDate();
  /**
   * <code>.google.protobuf.Int64Value date = 3;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getDateOrBuilder();

  /**
   * <code>.google.protobuf.DoubleValue open = 4;</code>
   * @return Whether the open field is set.
   */
  boolean hasOpen();
  /**
   * <code>.google.protobuf.DoubleValue open = 4;</code>
   * @return The open.
   */
  com.google.protobuf.DoubleValue getOpen();
  /**
   * <code>.google.protobuf.DoubleValue open = 4;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getOpenOrBuilder();

  /**
   * <code>.google.protobuf.DoubleValue close = 5;</code>
   * @return Whether the close field is set.
   */
  boolean hasClose();
  /**
   * <code>.google.protobuf.DoubleValue close = 5;</code>
   * @return The close.
   */
  com.google.protobuf.DoubleValue getClose();
  /**
   * <code>.google.protobuf.DoubleValue close = 5;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getCloseOrBuilder();

  /**
   * <code>.google.protobuf.DoubleValue high = 6;</code>
   * @return Whether the high field is set.
   */
  boolean hasHigh();
  /**
   * <code>.google.protobuf.DoubleValue high = 6;</code>
   * @return The high.
   */
  com.google.protobuf.DoubleValue getHigh();
  /**
   * <code>.google.protobuf.DoubleValue high = 6;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getHighOrBuilder();

  /**
   * <code>.google.protobuf.DoubleValue low = 7;</code>
   * @return Whether the low field is set.
   */
  boolean hasLow();
  /**
   * <code>.google.protobuf.DoubleValue low = 7;</code>
   * @return The low.
   */
  com.google.protobuf.DoubleValue getLow();
  /**
   * <code>.google.protobuf.DoubleValue low = 7;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getLowOrBuilder();

  /**
   * <code>.google.protobuf.DoubleValue volume = 8;</code>
   * @return Whether the volume field is set.
   */
  boolean hasVolume();
  /**
   * <code>.google.protobuf.DoubleValue volume = 8;</code>
   * @return The volume.
   */
  com.google.protobuf.DoubleValue getVolume();
  /**
   * <code>.google.protobuf.DoubleValue volume = 8;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getVolumeOrBuilder();
}
