// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks.proto

package br.ortiz.grpc.services;

/**
 * Protobuf type {@code services.QuoteMessage}
 */
public final class QuoteMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:services.QuoteMessage)
    QuoteMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QuoteMessage.newBuilder() to construct.
  private QuoteMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QuoteMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QuoteMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QuoteMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (id_ != null) {
              subBuilder = id_.toBuilder();
            }
            id_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(id_);
              id_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (symbol_ != null) {
              subBuilder = symbol_.toBuilder();
            }
            symbol_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(symbol_);
              symbol_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (date_ != null) {
              subBuilder = date_.toBuilder();
            }
            date_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(date_);
              date_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.DoubleValue.Builder subBuilder = null;
            if (open_ != null) {
              subBuilder = open_.toBuilder();
            }
            open_ = input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(open_);
              open_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.DoubleValue.Builder subBuilder = null;
            if (close_ != null) {
              subBuilder = close_.toBuilder();
            }
            close_ = input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(close_);
              close_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.protobuf.DoubleValue.Builder subBuilder = null;
            if (high_ != null) {
              subBuilder = high_.toBuilder();
            }
            high_ = input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(high_);
              high_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.DoubleValue.Builder subBuilder = null;
            if (low_ != null) {
              subBuilder = low_.toBuilder();
            }
            low_ = input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(low_);
              low_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.google.protobuf.DoubleValue.Builder subBuilder = null;
            if (volume_ != null) {
              subBuilder = volume_.toBuilder();
            }
            volume_ = input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(volume_);
              volume_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.ortiz.grpc.services.Stocks.internal_static_services_QuoteMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.ortiz.grpc.services.Stocks.internal_static_services_QuoteMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.ortiz.grpc.services.QuoteMessage.class, br.ortiz.grpc.services.QuoteMessage.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private com.google.protobuf.Int64Value id_;
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public com.google.protobuf.Int64Value getId() {
    return id_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : id_;
  }
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder() {
    return getId();
  }

  public static final int SYMBOL_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue symbol_;
  /**
   * <code>.google.protobuf.StringValue symbol = 2;</code>
   * @return Whether the symbol field is set.
   */
  @java.lang.Override
  public boolean hasSymbol() {
    return symbol_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue symbol = 2;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getSymbol() {
    return symbol_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : symbol_;
  }
  /**
   * <code>.google.protobuf.StringValue symbol = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getSymbolOrBuilder() {
    return getSymbol();
  }

  public static final int DATE_FIELD_NUMBER = 3;
  private com.google.protobuf.Int64Value date_;
  /**
   * <code>.google.protobuf.Int64Value date = 3;</code>
   * @return Whether the date field is set.
   */
  @java.lang.Override
  public boolean hasDate() {
    return date_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value date = 3;</code>
   * @return The date.
   */
  @java.lang.Override
  public com.google.protobuf.Int64Value getDate() {
    return date_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : date_;
  }
  /**
   * <code>.google.protobuf.Int64Value date = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int64ValueOrBuilder getDateOrBuilder() {
    return getDate();
  }

  public static final int OPEN_FIELD_NUMBER = 4;
  private com.google.protobuf.DoubleValue open_;
  /**
   * <code>.google.protobuf.DoubleValue open = 4;</code>
   * @return Whether the open field is set.
   */
  @java.lang.Override
  public boolean hasOpen() {
    return open_ != null;
  }
  /**
   * <code>.google.protobuf.DoubleValue open = 4;</code>
   * @return The open.
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValue getOpen() {
    return open_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : open_;
  }
  /**
   * <code>.google.protobuf.DoubleValue open = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValueOrBuilder getOpenOrBuilder() {
    return getOpen();
  }

  public static final int CLOSE_FIELD_NUMBER = 5;
  private com.google.protobuf.DoubleValue close_;
  /**
   * <code>.google.protobuf.DoubleValue close = 5;</code>
   * @return Whether the close field is set.
   */
  @java.lang.Override
  public boolean hasClose() {
    return close_ != null;
  }
  /**
   * <code>.google.protobuf.DoubleValue close = 5;</code>
   * @return The close.
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValue getClose() {
    return close_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : close_;
  }
  /**
   * <code>.google.protobuf.DoubleValue close = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValueOrBuilder getCloseOrBuilder() {
    return getClose();
  }

  public static final int HIGH_FIELD_NUMBER = 6;
  private com.google.protobuf.DoubleValue high_;
  /**
   * <code>.google.protobuf.DoubleValue high = 6;</code>
   * @return Whether the high field is set.
   */
  @java.lang.Override
  public boolean hasHigh() {
    return high_ != null;
  }
  /**
   * <code>.google.protobuf.DoubleValue high = 6;</code>
   * @return The high.
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValue getHigh() {
    return high_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : high_;
  }
  /**
   * <code>.google.protobuf.DoubleValue high = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValueOrBuilder getHighOrBuilder() {
    return getHigh();
  }

  public static final int LOW_FIELD_NUMBER = 7;
  private com.google.protobuf.DoubleValue low_;
  /**
   * <code>.google.protobuf.DoubleValue low = 7;</code>
   * @return Whether the low field is set.
   */
  @java.lang.Override
  public boolean hasLow() {
    return low_ != null;
  }
  /**
   * <code>.google.protobuf.DoubleValue low = 7;</code>
   * @return The low.
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValue getLow() {
    return low_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : low_;
  }
  /**
   * <code>.google.protobuf.DoubleValue low = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValueOrBuilder getLowOrBuilder() {
    return getLow();
  }

  public static final int VOLUME_FIELD_NUMBER = 8;
  private com.google.protobuf.DoubleValue volume_;
  /**
   * <code>.google.protobuf.DoubleValue volume = 8;</code>
   * @return Whether the volume field is set.
   */
  @java.lang.Override
  public boolean hasVolume() {
    return volume_ != null;
  }
  /**
   * <code>.google.protobuf.DoubleValue volume = 8;</code>
   * @return The volume.
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValue getVolume() {
    return volume_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : volume_;
  }
  /**
   * <code>.google.protobuf.DoubleValue volume = 8;</code>
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValueOrBuilder getVolumeOrBuilder() {
    return getVolume();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (symbol_ != null) {
      output.writeMessage(2, getSymbol());
    }
    if (date_ != null) {
      output.writeMessage(3, getDate());
    }
    if (open_ != null) {
      output.writeMessage(4, getOpen());
    }
    if (close_ != null) {
      output.writeMessage(5, getClose());
    }
    if (high_ != null) {
      output.writeMessage(6, getHigh());
    }
    if (low_ != null) {
      output.writeMessage(7, getLow());
    }
    if (volume_ != null) {
      output.writeMessage(8, getVolume());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (symbol_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSymbol());
    }
    if (date_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDate());
    }
    if (open_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getOpen());
    }
    if (close_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getClose());
    }
    if (high_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getHigh());
    }
    if (low_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getLow());
    }
    if (volume_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getVolume());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.ortiz.grpc.services.QuoteMessage)) {
      return super.equals(obj);
    }
    br.ortiz.grpc.services.QuoteMessage other = (br.ortiz.grpc.services.QuoteMessage) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasSymbol() != other.hasSymbol()) return false;
    if (hasSymbol()) {
      if (!getSymbol()
          .equals(other.getSymbol())) return false;
    }
    if (hasDate() != other.hasDate()) return false;
    if (hasDate()) {
      if (!getDate()
          .equals(other.getDate())) return false;
    }
    if (hasOpen() != other.hasOpen()) return false;
    if (hasOpen()) {
      if (!getOpen()
          .equals(other.getOpen())) return false;
    }
    if (hasClose() != other.hasClose()) return false;
    if (hasClose()) {
      if (!getClose()
          .equals(other.getClose())) return false;
    }
    if (hasHigh() != other.hasHigh()) return false;
    if (hasHigh()) {
      if (!getHigh()
          .equals(other.getHigh())) return false;
    }
    if (hasLow() != other.hasLow()) return false;
    if (hasLow()) {
      if (!getLow()
          .equals(other.getLow())) return false;
    }
    if (hasVolume() != other.hasVolume()) return false;
    if (hasVolume()) {
      if (!getVolume()
          .equals(other.getVolume())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasSymbol()) {
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
    }
    if (hasDate()) {
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
    }
    if (hasOpen()) {
      hash = (37 * hash) + OPEN_FIELD_NUMBER;
      hash = (53 * hash) + getOpen().hashCode();
    }
    if (hasClose()) {
      hash = (37 * hash) + CLOSE_FIELD_NUMBER;
      hash = (53 * hash) + getClose().hashCode();
    }
    if (hasHigh()) {
      hash = (37 * hash) + HIGH_FIELD_NUMBER;
      hash = (53 * hash) + getHigh().hashCode();
    }
    if (hasLow()) {
      hash = (37 * hash) + LOW_FIELD_NUMBER;
      hash = (53 * hash) + getLow().hashCode();
    }
    if (hasVolume()) {
      hash = (37 * hash) + VOLUME_FIELD_NUMBER;
      hash = (53 * hash) + getVolume().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.ortiz.grpc.services.QuoteMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ortiz.grpc.services.QuoteMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ortiz.grpc.services.QuoteMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ortiz.grpc.services.QuoteMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ortiz.grpc.services.QuoteMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.ortiz.grpc.services.QuoteMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.ortiz.grpc.services.QuoteMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.ortiz.grpc.services.QuoteMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ortiz.grpc.services.QuoteMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.ortiz.grpc.services.QuoteMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.ortiz.grpc.services.QuoteMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.ortiz.grpc.services.QuoteMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.ortiz.grpc.services.QuoteMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code services.QuoteMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:services.QuoteMessage)
      br.ortiz.grpc.services.QuoteMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ortiz.grpc.services.Stocks.internal_static_services_QuoteMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ortiz.grpc.services.Stocks.internal_static_services_QuoteMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ortiz.grpc.services.QuoteMessage.class, br.ortiz.grpc.services.QuoteMessage.Builder.class);
    }

    // Construct using br.ortiz.grpc.services.QuoteMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (idBuilder_ == null) {
        id_ = null;
      } else {
        id_ = null;
        idBuilder_ = null;
      }
      if (symbolBuilder_ == null) {
        symbol_ = null;
      } else {
        symbol_ = null;
        symbolBuilder_ = null;
      }
      if (dateBuilder_ == null) {
        date_ = null;
      } else {
        date_ = null;
        dateBuilder_ = null;
      }
      if (openBuilder_ == null) {
        open_ = null;
      } else {
        open_ = null;
        openBuilder_ = null;
      }
      if (closeBuilder_ == null) {
        close_ = null;
      } else {
        close_ = null;
        closeBuilder_ = null;
      }
      if (highBuilder_ == null) {
        high_ = null;
      } else {
        high_ = null;
        highBuilder_ = null;
      }
      if (lowBuilder_ == null) {
        low_ = null;
      } else {
        low_ = null;
        lowBuilder_ = null;
      }
      if (volumeBuilder_ == null) {
        volume_ = null;
      } else {
        volume_ = null;
        volumeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.ortiz.grpc.services.Stocks.internal_static_services_QuoteMessage_descriptor;
    }

    @java.lang.Override
    public br.ortiz.grpc.services.QuoteMessage getDefaultInstanceForType() {
      return br.ortiz.grpc.services.QuoteMessage.getDefaultInstance();
    }

    @java.lang.Override
    public br.ortiz.grpc.services.QuoteMessage build() {
      br.ortiz.grpc.services.QuoteMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.ortiz.grpc.services.QuoteMessage buildPartial() {
      br.ortiz.grpc.services.QuoteMessage result = new br.ortiz.grpc.services.QuoteMessage(this);
      if (idBuilder_ == null) {
        result.id_ = id_;
      } else {
        result.id_ = idBuilder_.build();
      }
      if (symbolBuilder_ == null) {
        result.symbol_ = symbol_;
      } else {
        result.symbol_ = symbolBuilder_.build();
      }
      if (dateBuilder_ == null) {
        result.date_ = date_;
      } else {
        result.date_ = dateBuilder_.build();
      }
      if (openBuilder_ == null) {
        result.open_ = open_;
      } else {
        result.open_ = openBuilder_.build();
      }
      if (closeBuilder_ == null) {
        result.close_ = close_;
      } else {
        result.close_ = closeBuilder_.build();
      }
      if (highBuilder_ == null) {
        result.high_ = high_;
      } else {
        result.high_ = highBuilder_.build();
      }
      if (lowBuilder_ == null) {
        result.low_ = low_;
      } else {
        result.low_ = lowBuilder_.build();
      }
      if (volumeBuilder_ == null) {
        result.volume_ = volume_;
      } else {
        result.volume_ = volumeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.ortiz.grpc.services.QuoteMessage) {
        return mergeFrom((br.ortiz.grpc.services.QuoteMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.ortiz.grpc.services.QuoteMessage other) {
      if (other == br.ortiz.grpc.services.QuoteMessage.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.hasSymbol()) {
        mergeSymbol(other.getSymbol());
      }
      if (other.hasDate()) {
        mergeDate(other.getDate());
      }
      if (other.hasOpen()) {
        mergeOpen(other.getOpen());
      }
      if (other.hasClose()) {
        mergeClose(other.getClose());
      }
      if (other.hasHigh()) {
        mergeHigh(other.getHigh());
      }
      if (other.hasLow()) {
        mergeLow(other.getLow());
      }
      if (other.hasVolume()) {
        mergeVolume(other.getVolume());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.ortiz.grpc.services.QuoteMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.ortiz.grpc.services.QuoteMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Int64Value id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> idBuilder_;
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return idBuilder_ != null || id_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     * @return The id.
     */
    public com.google.protobuf.Int64Value getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public Builder setId(com.google.protobuf.Int64Value value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
        onChanged();
      } else {
        idBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public Builder setId(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
        onChanged();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public Builder mergeId(com.google.protobuf.Int64Value value) {
      if (idBuilder_ == null) {
        if (id_ != null) {
          id_ =
            com.google.protobuf.Int64Value.newBuilder(id_).mergeFrom(value).buildPartial();
        } else {
          id_ = value;
        }
        onChanged();
      } else {
        idBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public Builder clearId() {
      if (idBuilder_ == null) {
        id_ = null;
        onChanged();
      } else {
        id_ = null;
        idBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public com.google.protobuf.Int64Value.Builder getIdBuilder() {
      
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private com.google.protobuf.StringValue symbol_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> symbolBuilder_;
    /**
     * <code>.google.protobuf.StringValue symbol = 2;</code>
     * @return Whether the symbol field is set.
     */
    public boolean hasSymbol() {
      return symbolBuilder_ != null || symbol_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue symbol = 2;</code>
     * @return The symbol.
     */
    public com.google.protobuf.StringValue getSymbol() {
      if (symbolBuilder_ == null) {
        return symbol_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : symbol_;
      } else {
        return symbolBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue symbol = 2;</code>
     */
    public Builder setSymbol(com.google.protobuf.StringValue value) {
      if (symbolBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        symbol_ = value;
        onChanged();
      } else {
        symbolBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue symbol = 2;</code>
     */
    public Builder setSymbol(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (symbolBuilder_ == null) {
        symbol_ = builderForValue.build();
        onChanged();
      } else {
        symbolBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue symbol = 2;</code>
     */
    public Builder mergeSymbol(com.google.protobuf.StringValue value) {
      if (symbolBuilder_ == null) {
        if (symbol_ != null) {
          symbol_ =
            com.google.protobuf.StringValue.newBuilder(symbol_).mergeFrom(value).buildPartial();
        } else {
          symbol_ = value;
        }
        onChanged();
      } else {
        symbolBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue symbol = 2;</code>
     */
    public Builder clearSymbol() {
      if (symbolBuilder_ == null) {
        symbol_ = null;
        onChanged();
      } else {
        symbol_ = null;
        symbolBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue symbol = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getSymbolBuilder() {
      
      onChanged();
      return getSymbolFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue symbol = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getSymbolOrBuilder() {
      if (symbolBuilder_ != null) {
        return symbolBuilder_.getMessageOrBuilder();
      } else {
        return symbol_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : symbol_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue symbol = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getSymbolFieldBuilder() {
      if (symbolBuilder_ == null) {
        symbolBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getSymbol(),
                getParentForChildren(),
                isClean());
        symbol_ = null;
      }
      return symbolBuilder_;
    }

    private com.google.protobuf.Int64Value date_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> dateBuilder_;
    /**
     * <code>.google.protobuf.Int64Value date = 3;</code>
     * @return Whether the date field is set.
     */
    public boolean hasDate() {
      return dateBuilder_ != null || date_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value date = 3;</code>
     * @return The date.
     */
    public com.google.protobuf.Int64Value getDate() {
      if (dateBuilder_ == null) {
        return date_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : date_;
      } else {
        return dateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value date = 3;</code>
     */
    public Builder setDate(com.google.protobuf.Int64Value value) {
      if (dateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        date_ = value;
        onChanged();
      } else {
        dateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value date = 3;</code>
     */
    public Builder setDate(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (dateBuilder_ == null) {
        date_ = builderForValue.build();
        onChanged();
      } else {
        dateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value date = 3;</code>
     */
    public Builder mergeDate(com.google.protobuf.Int64Value value) {
      if (dateBuilder_ == null) {
        if (date_ != null) {
          date_ =
            com.google.protobuf.Int64Value.newBuilder(date_).mergeFrom(value).buildPartial();
        } else {
          date_ = value;
        }
        onChanged();
      } else {
        dateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value date = 3;</code>
     */
    public Builder clearDate() {
      if (dateBuilder_ == null) {
        date_ = null;
        onChanged();
      } else {
        date_ = null;
        dateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value date = 3;</code>
     */
    public com.google.protobuf.Int64Value.Builder getDateBuilder() {
      
      onChanged();
      return getDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value date = 3;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getDateOrBuilder() {
      if (dateBuilder_ != null) {
        return dateBuilder_.getMessageOrBuilder();
      } else {
        return date_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : date_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value date = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getDateFieldBuilder() {
      if (dateBuilder_ == null) {
        dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getDate(),
                getParentForChildren(),
                isClean());
        date_ = null;
      }
      return dateBuilder_;
    }

    private com.google.protobuf.DoubleValue open_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> openBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue open = 4;</code>
     * @return Whether the open field is set.
     */
    public boolean hasOpen() {
      return openBuilder_ != null || open_ != null;
    }
    /**
     * <code>.google.protobuf.DoubleValue open = 4;</code>
     * @return The open.
     */
    public com.google.protobuf.DoubleValue getOpen() {
      if (openBuilder_ == null) {
        return open_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : open_;
      } else {
        return openBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue open = 4;</code>
     */
    public Builder setOpen(com.google.protobuf.DoubleValue value) {
      if (openBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        open_ = value;
        onChanged();
      } else {
        openBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue open = 4;</code>
     */
    public Builder setOpen(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (openBuilder_ == null) {
        open_ = builderForValue.build();
        onChanged();
      } else {
        openBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue open = 4;</code>
     */
    public Builder mergeOpen(com.google.protobuf.DoubleValue value) {
      if (openBuilder_ == null) {
        if (open_ != null) {
          open_ =
            com.google.protobuf.DoubleValue.newBuilder(open_).mergeFrom(value).buildPartial();
        } else {
          open_ = value;
        }
        onChanged();
      } else {
        openBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue open = 4;</code>
     */
    public Builder clearOpen() {
      if (openBuilder_ == null) {
        open_ = null;
        onChanged();
      } else {
        open_ = null;
        openBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue open = 4;</code>
     */
    public com.google.protobuf.DoubleValue.Builder getOpenBuilder() {
      
      onChanged();
      return getOpenFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue open = 4;</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getOpenOrBuilder() {
      if (openBuilder_ != null) {
        return openBuilder_.getMessageOrBuilder();
      } else {
        return open_ == null ?
            com.google.protobuf.DoubleValue.getDefaultInstance() : open_;
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue open = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getOpenFieldBuilder() {
      if (openBuilder_ == null) {
        openBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                getOpen(),
                getParentForChildren(),
                isClean());
        open_ = null;
      }
      return openBuilder_;
    }

    private com.google.protobuf.DoubleValue close_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> closeBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue close = 5;</code>
     * @return Whether the close field is set.
     */
    public boolean hasClose() {
      return closeBuilder_ != null || close_ != null;
    }
    /**
     * <code>.google.protobuf.DoubleValue close = 5;</code>
     * @return The close.
     */
    public com.google.protobuf.DoubleValue getClose() {
      if (closeBuilder_ == null) {
        return close_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : close_;
      } else {
        return closeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue close = 5;</code>
     */
    public Builder setClose(com.google.protobuf.DoubleValue value) {
      if (closeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        close_ = value;
        onChanged();
      } else {
        closeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue close = 5;</code>
     */
    public Builder setClose(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (closeBuilder_ == null) {
        close_ = builderForValue.build();
        onChanged();
      } else {
        closeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue close = 5;</code>
     */
    public Builder mergeClose(com.google.protobuf.DoubleValue value) {
      if (closeBuilder_ == null) {
        if (close_ != null) {
          close_ =
            com.google.protobuf.DoubleValue.newBuilder(close_).mergeFrom(value).buildPartial();
        } else {
          close_ = value;
        }
        onChanged();
      } else {
        closeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue close = 5;</code>
     */
    public Builder clearClose() {
      if (closeBuilder_ == null) {
        close_ = null;
        onChanged();
      } else {
        close_ = null;
        closeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue close = 5;</code>
     */
    public com.google.protobuf.DoubleValue.Builder getCloseBuilder() {
      
      onChanged();
      return getCloseFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue close = 5;</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getCloseOrBuilder() {
      if (closeBuilder_ != null) {
        return closeBuilder_.getMessageOrBuilder();
      } else {
        return close_ == null ?
            com.google.protobuf.DoubleValue.getDefaultInstance() : close_;
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue close = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getCloseFieldBuilder() {
      if (closeBuilder_ == null) {
        closeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                getClose(),
                getParentForChildren(),
                isClean());
        close_ = null;
      }
      return closeBuilder_;
    }

    private com.google.protobuf.DoubleValue high_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> highBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue high = 6;</code>
     * @return Whether the high field is set.
     */
    public boolean hasHigh() {
      return highBuilder_ != null || high_ != null;
    }
    /**
     * <code>.google.protobuf.DoubleValue high = 6;</code>
     * @return The high.
     */
    public com.google.protobuf.DoubleValue getHigh() {
      if (highBuilder_ == null) {
        return high_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : high_;
      } else {
        return highBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue high = 6;</code>
     */
    public Builder setHigh(com.google.protobuf.DoubleValue value) {
      if (highBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        high_ = value;
        onChanged();
      } else {
        highBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue high = 6;</code>
     */
    public Builder setHigh(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (highBuilder_ == null) {
        high_ = builderForValue.build();
        onChanged();
      } else {
        highBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue high = 6;</code>
     */
    public Builder mergeHigh(com.google.protobuf.DoubleValue value) {
      if (highBuilder_ == null) {
        if (high_ != null) {
          high_ =
            com.google.protobuf.DoubleValue.newBuilder(high_).mergeFrom(value).buildPartial();
        } else {
          high_ = value;
        }
        onChanged();
      } else {
        highBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue high = 6;</code>
     */
    public Builder clearHigh() {
      if (highBuilder_ == null) {
        high_ = null;
        onChanged();
      } else {
        high_ = null;
        highBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue high = 6;</code>
     */
    public com.google.protobuf.DoubleValue.Builder getHighBuilder() {
      
      onChanged();
      return getHighFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue high = 6;</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getHighOrBuilder() {
      if (highBuilder_ != null) {
        return highBuilder_.getMessageOrBuilder();
      } else {
        return high_ == null ?
            com.google.protobuf.DoubleValue.getDefaultInstance() : high_;
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue high = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getHighFieldBuilder() {
      if (highBuilder_ == null) {
        highBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                getHigh(),
                getParentForChildren(),
                isClean());
        high_ = null;
      }
      return highBuilder_;
    }

    private com.google.protobuf.DoubleValue low_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> lowBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue low = 7;</code>
     * @return Whether the low field is set.
     */
    public boolean hasLow() {
      return lowBuilder_ != null || low_ != null;
    }
    /**
     * <code>.google.protobuf.DoubleValue low = 7;</code>
     * @return The low.
     */
    public com.google.protobuf.DoubleValue getLow() {
      if (lowBuilder_ == null) {
        return low_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : low_;
      } else {
        return lowBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue low = 7;</code>
     */
    public Builder setLow(com.google.protobuf.DoubleValue value) {
      if (lowBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        low_ = value;
        onChanged();
      } else {
        lowBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue low = 7;</code>
     */
    public Builder setLow(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (lowBuilder_ == null) {
        low_ = builderForValue.build();
        onChanged();
      } else {
        lowBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue low = 7;</code>
     */
    public Builder mergeLow(com.google.protobuf.DoubleValue value) {
      if (lowBuilder_ == null) {
        if (low_ != null) {
          low_ =
            com.google.protobuf.DoubleValue.newBuilder(low_).mergeFrom(value).buildPartial();
        } else {
          low_ = value;
        }
        onChanged();
      } else {
        lowBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue low = 7;</code>
     */
    public Builder clearLow() {
      if (lowBuilder_ == null) {
        low_ = null;
        onChanged();
      } else {
        low_ = null;
        lowBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue low = 7;</code>
     */
    public com.google.protobuf.DoubleValue.Builder getLowBuilder() {
      
      onChanged();
      return getLowFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue low = 7;</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getLowOrBuilder() {
      if (lowBuilder_ != null) {
        return lowBuilder_.getMessageOrBuilder();
      } else {
        return low_ == null ?
            com.google.protobuf.DoubleValue.getDefaultInstance() : low_;
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue low = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getLowFieldBuilder() {
      if (lowBuilder_ == null) {
        lowBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                getLow(),
                getParentForChildren(),
                isClean());
        low_ = null;
      }
      return lowBuilder_;
    }

    private com.google.protobuf.DoubleValue volume_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> volumeBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue volume = 8;</code>
     * @return Whether the volume field is set.
     */
    public boolean hasVolume() {
      return volumeBuilder_ != null || volume_ != null;
    }
    /**
     * <code>.google.protobuf.DoubleValue volume = 8;</code>
     * @return The volume.
     */
    public com.google.protobuf.DoubleValue getVolume() {
      if (volumeBuilder_ == null) {
        return volume_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : volume_;
      } else {
        return volumeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue volume = 8;</code>
     */
    public Builder setVolume(com.google.protobuf.DoubleValue value) {
      if (volumeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        volume_ = value;
        onChanged();
      } else {
        volumeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue volume = 8;</code>
     */
    public Builder setVolume(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (volumeBuilder_ == null) {
        volume_ = builderForValue.build();
        onChanged();
      } else {
        volumeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue volume = 8;</code>
     */
    public Builder mergeVolume(com.google.protobuf.DoubleValue value) {
      if (volumeBuilder_ == null) {
        if (volume_ != null) {
          volume_ =
            com.google.protobuf.DoubleValue.newBuilder(volume_).mergeFrom(value).buildPartial();
        } else {
          volume_ = value;
        }
        onChanged();
      } else {
        volumeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue volume = 8;</code>
     */
    public Builder clearVolume() {
      if (volumeBuilder_ == null) {
        volume_ = null;
        onChanged();
      } else {
        volume_ = null;
        volumeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue volume = 8;</code>
     */
    public com.google.protobuf.DoubleValue.Builder getVolumeBuilder() {
      
      onChanged();
      return getVolumeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue volume = 8;</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getVolumeOrBuilder() {
      if (volumeBuilder_ != null) {
        return volumeBuilder_.getMessageOrBuilder();
      } else {
        return volume_ == null ?
            com.google.protobuf.DoubleValue.getDefaultInstance() : volume_;
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue volume = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getVolumeFieldBuilder() {
      if (volumeBuilder_ == null) {
        volumeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                getVolume(),
                getParentForChildren(),
                isClean());
        volume_ = null;
      }
      return volumeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:services.QuoteMessage)
  }

  // @@protoc_insertion_point(class_scope:services.QuoteMessage)
  private static final br.ortiz.grpc.services.QuoteMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.ortiz.grpc.services.QuoteMessage();
  }

  public static br.ortiz.grpc.services.QuoteMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QuoteMessage>
      PARSER = new com.google.protobuf.AbstractParser<QuoteMessage>() {
    @java.lang.Override
    public QuoteMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QuoteMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QuoteMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QuoteMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.ortiz.grpc.services.QuoteMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

