// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks.proto

package br.ortiz.grpc.services;

public final class Stocks {
  private Stocks() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_QuoteMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_QuoteMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_QuoteQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_QuoteQuery_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014stocks.proto\022\010services\032\036google/protobu" +
      "f/wrappers.proto\"\356\002\n\014QuoteMessage\022\'\n\002id\030" +
      "\001 \001(\0132\033.google.protobuf.Int64Value\022,\n\006sy" +
      "mbol\030\002 \001(\0132\034.google.protobuf.StringValue" +
      "\022)\n\004date\030\003 \001(\0132\033.google.protobuf.Int64Va" +
      "lue\022*\n\004open\030\004 \001(\0132\034.google.protobuf.Doub" +
      "leValue\022+\n\005close\030\005 \001(\0132\034.google.protobuf" +
      ".DoubleValue\022*\n\004high\030\006 \001(\0132\034.google.prot" +
      "obuf.DoubleValue\022)\n\003low\030\007 \001(\0132\034.google.p" +
      "rotobuf.DoubleValue\022,\n\006volume\030\010 \001(\0132\034.go" +
      "ogle.protobuf.DoubleValue\":\n\nQuoteQuery\022" +
      ",\n\006symbol\030\001 \001(\0132\034.google.protobuf.String" +
      "Value2\203\001\n\014StockService\022:\n\006Insert\022\026.servi" +
      "ces.QuoteMessage\032\026.services.QuoteMessage" +
      "\"\000\0227\n\003Get\022\024.services.QuoteQuery\032\026.servic" +
      "es.QuoteMessage\"\0000\001B\034\n\026br.ortiz.grpc.ser" +
      "vicesP\001Z\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_services_QuoteMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_services_QuoteMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_QuoteMessage_descriptor,
        new java.lang.String[] { "Id", "Symbol", "Date", "Open", "Close", "High", "Low", "Volume", });
    internal_static_services_QuoteQuery_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_services_QuoteQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_QuoteQuery_descriptor,
        new java.lang.String[] { "Symbol", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
