{
 "title": "My SPG",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "REST - Routes Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "POST Rate Stock Prices",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(avg_over_time(http_server_requests_seconds_count{uri=\"/stock-quotes\", method=\"POST\", outcome=\"SUCCESS\"}[5m])) / sum(avg_over_time(http_server_requests_seconds_count{uri=\"/stock-quotes\", method=\"POST\"}[5m]))"
    }
   ]
  },
  {
   "title": "GET Rate Stock Prices",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(avg_over_time(http_server_requests_seconds_count{uri=\"/stock-quotes\", method=\"GET\", outcome=\"SUCCESS\"}[5m])) / sum(avg_over_time(http_server_requests_seconds_count{uri=\"/stock-quotes\", method=\"GET\"}[5m]))"
    }
   ]
  },
  { "title": "gRPC Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "gRPC - Stocks Insert Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(avg_over_time(grpc_server_processing_duration_seconds_count{service=\"services.StockService\", method=\"Insert\", statusCode=\"OK\"}[5m])) / sum(avg_over_time(grpc_server_processing_duration_seconds_count{service=\"services.StockService\", method=\"Insert\"}[5m]))"
    }
   ]
  },
  {
   "title": "gRPC - Stocks GET Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(avg_over_time(grpc_server_processing_duration_seconds_count{service=\"services.StockService\", method=\"Get\", statusCode=\"OK\"}[5m])) / sum(avg_over_time(grpc_server_processing_duration_seconds_count{service=\"services.StockService\", method=\"Get\"}[5m]))"
    }
   ]
  },
  { "title": "Resources Machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "yaxes": [
    { "format": "cpu" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_vss_bytes{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Virtual Set  Usage"
    },
    {
     "expr": "process_memory_rss_bytes{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Resident Set Size Usage"
    },
    {
     "expr": "process_memory_swap_bytes{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Swap Usage"
    }
   ]
  }
 ]
}